config/routes.rb
Rails.application.routes.draw do
  root 'todo#index'
  get 'todo/update'
  post 'todo/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
    @projects = Project.all
  end

  def update
  end

  def create
    @todo = Todo.new(params.require(:todo).permit(:text, :project_id))
    print @todo
    @todo.save
    redirect_to(:root)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo/create.html.erb
<h1>Todo#create</h1>
<p>Find me in app/views/todo/create.html.erb</p>

app/views/todo/index.html.erb
<div>
  <h1>Задачи</h1>

  <% @projects.each do |project| %>
    <h2><%= project.title %></h2>
    <ul>
      <% project.todos.each do |todo| %>
        <li><%= todo.text %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div>
  <h1>Новая задача</h1>
  <a id="add-todo" href="#">
    <%= image_tag("addTodoIcon.png", :alt => "Добавить задачу") %>
  </a>
  <%= form_with scope: :todo, id: "create-todo", url: todo_create_path, local: true do |form| %>
    <p>
      <%= form.text_field :text, placeholder: "Название задачи..." %>
    </p>
    <%= form.select(:project_id, options_for_select(Project.all.map { |p| [ p.title, p.id ] })) %>
    <p>
      <%= link_to "ОТМЕНА", '#', id: "cancel-btn" %>
      <%= link_to 'ОК', "#", :onclick => "$('#create-todo').submit()" %>
    </p>

  <% end %>
</div>

app/views/todo/update.html.erb
<h1>Todo#update</h1>
<p>Find me in app/views/todo/update.html.erb</p>